spring:
  datasource:
    url: jdbc:mysql://150.158.167.162:3306/springboot_react?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
    username: root
    password: lmzs1111
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

#mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  ip : localhost